Cargo.toml
README.md
src/lib.rs
tests/check-versions.rs

The old name was not very description and did not describe what the crate does: it gives you tools to keep version numbers in sync.
To accomplish this, a final version 0.1.1 has been released of `check-versions`. This version is identical to version 0.1.0, except that a deprecation warning is emitted when it's used. The warning instructs users to switch to the `version-sync` crate, which has been released as version 0.1.2.

Rename crate to version-sync

---

README.md

I deleted the old project and added a new one, and forgot that this
would invalidate the AppVeyor badge URL.

readme: fix AppVeyor badge URL

---

Cargo.toml
src/lib.rs
tests/version-numbers.rs

This PR adds a new `check_html_root_url` function and a corresponding `assert_html_root_url_updated!` macro. These can be used to enforce updating of the `html_root_url` attribute as per [C-HTML-ROOT][1].
[1]: https://rust-lang-nursery.github.io/api-guidelines/documentation.html#crate-sets-html_root_url-attribute-c-html-root

Add functionality for checking html_root_url

---

README.md

The crate renaming is not terribly interesting and version 0.1.3 is
functionally identical to version 0.1.0. So that version is now the
first published version according to the changelog here.
This also fixes some broken links I managed to introduce while merging
the rename branch into master.

readme: collapse old versions in the changelog

---

README.md

It seems that crates.io use the local time of the upload as the date
of the release. Version 0.2.0 was uploaded just before midnight on the
19th of September UTC, but just after midnight if you use my local
timezone which is CEST.

readme: fix 0.2.0 release date

---

README.md
src/lib.rs

Similarly to how you can use no_run to exclude a block with Rust code
from being executed by rustdoc, you can now use no_sync to exclude
TOML blocks from being checked by the check_markdown_deps function.

is_toml_block: skip blocks with no_sync

---

.travis.yml

The `script` commands specified here are the default commands. So we can leave them out.

travis: remove commands that are default anyway

---

README.md
src/lib.rs

This updates the docstrings and the README to mention the `no_sync` flag.

Document no_sync

---

Cargo.toml
README.md
src/lib.rs

Before we completely ignored the pre-release identifiers when
comparing versions. This meant that a TOML block with
[dependencies]
foo = 1.0.0
was considered to match a crate version of 1.0.0-rc1. That was not
intended: per the semver specification, a pre-release version comes
before the normal version. So depending on version 1.0.0 would not
actually make it possible to install version 1.0.0-rc1.
Fixes #19.

version_matches_request: consider pre-release identifiers

---

.gitignore
Cargo.toml
README.md
src/lib.rs

It's a big dependency, slow to compile and not maintained anymore.
Moving to `syn`.
There is a caveat though: `version-sync` relied on span information
gathered from `syntex` to provide more helpful messages. `syn` 0.11.11
doesn't have such a functionality, though there are plans to incorporate
recent changes in procedural macro system to enable spans there too.
Current `syn` master contains such code, but is unstable.

lib: remove Syntex dependency

---

src/lib.rs

This simply refactors the code a little to reduce the amount of nesting in the parsing. We can probably reduce this further — perhaps with clever use of `and_then` on a `Result` type. I'll leave this for another time :-)

Refactor check_html_root_url

---

.travis.yml
README.md

Rust 1.17 is roughly four releases older than the current stable
release. Using this version will allow us to avoid pinning our
dependencies to old versions and will allow version-sync to be
packaged for Fedora (see #30).

travis: bump minimum Rust version to 1.17

---

src/lib.rs

The syn crate does not preserve span information while parsing the
Rust code, so we no longer have access to accurate information about
where each attribute begins and ends.
This adds a simple heuristic: we simply search for html_root_url in
the source code and use that line in the error message.

Better error reporting

---

.travis.yml
Cargo.toml
src/lib.rs

syn wasn't able to parse my lib.rs, likely because it didn't support
statement attributes. This should fix that, and it even makes a piece of
code slightly simpler.

Update to syn 0.14

---

.rustfmt.toml
src/lib.rs

This brings the formatting back in line with the defaults for rustfmt,
plus it reformats the file using a recent nightly rustfmt which means
the imports are now sorted.

rustfmt: standarize formatting

---

.travis.yml

This should help avoid situations like reported in #39 where the
minimum rustc requirements change without us noticing.

travis: run 'cargo update'

---

.appveyor.yml

This should help avoid situations like reported in #39 where the
minimum rustc requirements change without us noticing.

appveyor: run 'cargo update'

---

README.md
src/lib.rs

Before, a `foo = { git = '...' }` dependency would result in an error saying "no dependency on foo", which is clearly incorrect. We now simply ignore such Git dependencies since there is nothing for the crate author to update in such blocks.

Accept Git dependencies

---

README.md

readme: retroactively update minimum Rust version for 0.5.0

---

Cargo.toml
README.md
src/lib.rs
tests/version-numbers.rs

The new assert_contains_regex macro makes it easy to check that the
current version number is mentioned in a given file.
Fixes #17.

asser_contains-regex: new macro for more general regex checks

---

.travis.yml
Cargo.toml
README.md
src/contains_regex.rs
src/html_root_url.rs
src/lib.rs
src/markdown_deps.rs

This pull request updates the code to the Rust 2018 edition, which means that we now require Rust 1.31.0 or later.

Update to Rust 2018

---

Cargo.toml
README.md
src/html_root_url.rs

Before we used a heuristic by grepping the file for "html_root_url",
now we use the span information from the syn crate.

check_html_root_url: report accurate line numbers

---

README.md
src/lib.rs
tests/version-numbers.rs

With Rust 2018, we no longer need the macro_use attribute. Instead we
can simply use the macros like other items in the crate.
This simplifies the tests a bit.

doc: update example to use macros directly

---

README.md
tests/version-numbers.rs

Also check that the README contains the same version number as the
Travis config.

readme: show minimum supported rustc version

---

tests/version-numbers.rs

This prevents (unlikely) false positives.

tests: escape the version number

---

Cargo.toml

It turns out that you cannot publish a package on crates.io if it has
a wildcard dependency:
error: api errors: wildcard (`*`) dependency constraints are not
allowed on crates.io.

cargo: fix version of proc-macro2

---

src/markdown_deps.rs

The latest minor version of the toml crate seems to give more detailed
error output.

markdown_deps: handle test output from toml 0.5.3

---

.circleci/config.yml

This way we can specify the necessary Docker security options to let
Tarpaulin run while still getting the benefits of using a prebuilt
Docker image.

circleci: run cargo tarpaulin in a machine image

---

Cargo.toml
src/html_root_url.rs

Update to syn 1.0 and proc-macro2 1.0

---

Cargo.toml

This should hopefully will make it clearer when the version
requirements of dependencies can be bumped.
Closes #70, closes #80.

cargo: be explicit about Rust 2018 compatible versions

---

.appveyor.yml
.travis.yml
Cargo.toml
README.md
src/markdown_deps.rs
tests/version-numbers.rs

I've been trying to keep the crate compatible with Rust 2018, which
corresponds to Rust version 1.31.0. However, this has proven
impossible because of how our dependencies keep releasing new patch
versions that push up the minimum required Rust version.
Because of this, the current code no longer compiles with Rust 1.31.0
because `cargo sync` will pull in too new versions of the direct and
transitive dependencies. This happens even if there are no changes in
`version-sync`.
The failure to compile shows up as spurious and unexpected build
failures in our CI, which in turn makes it hard to trust CI.
I'm concluding that it's infeasible to keep `version-sync` compatible
with any particular version of Rust. While not perfect, we'll track
the latest stable version of Rust from now on. This is …

Drop Rust 2018 compatibility

---

src/markdown_deps.rs

If a TOML block was found inside a Markdown blockquote, we would
report a TOML parse error. This is because we extracted the code block
directly from the original text and thus incorrectly included the `>`
characters.
So parsing
~~~
> This is a blockquote
>
> ```toml
> clap = { git = "https://github.com/clap-rs/clap/" }
> ```
~~~
would result in an error like this:
> README.md (line 22) ... TOML parse error: unexpected character
>  found: `>` at line 1 column 1 in
>
> `> clap = { git = "https://github.com/clap-rs/clap/" }`
To fix this, we now parse the code blocks by listening to the `Start`
and `End` events from `pulldown-cmark`. This should be much more
robust.
Fixes #83.

Parse TOML blocks inside blockquotes

---

.appveyor.yml

This avoids downloading things like documentation, which in turn
should speed up builds.

appveyor: use minimal rustup profile

---

Cargo.toml
src/helpers.rs

This PR removes these crates from the dependency tree of `version-sync`:
- `itertools`
- `either`
- `aho-corasick`
- `thread_local`
- `lazy_static`
To remove `itertools` and `either`, I reimplemented a free function for joining an iterator with a separator. The implementation is short and fairly straightforward, which I hope means the maintenance burden is acceptable. This also allows removing an entire crate with only 15 lines of code.
To remove the remaining dependencies, I deactivated all `regex` features except `std` and `unicode`.
Thank you for the great tests! They made it easy to see what was safe to remove.

Pull in fewer dependencies

---

Cargo.toml
src/contains_regex.rs
src/helpers.rs

The regex crate only considers "\n" a line boundary, so ^ and $ don't
match "\r\n". This can be a problem if code is checked out on Windows
and Git helpfully rewrites your "\n" to "\r\n". I ran into this
problem when testing GitHub Actions on the textwrap repository.
See https://github.com/rust-lang/regex/issues/244.

Normalize "\r\n" to "\n" to ensure ^ and $ match line boundaries

---

src/lib.rs

See https://github.com/rust-lang/rust/pull/81645, https://github.com/rust-lang/rust/pull/81729.
Because this crate's public API is several macros, this lint does not get capped: the tokens are directly included in the local crate, which triggers the error.
Here's a failing workflow run on the latest nightly: https://github.com/artichoke/intaglio/runs/1867615715?check_suite_focus=true.

Fix non_fmt_panic lint error in latest nightly

---

README.md
tests/version-numbers.rs

These dates are more homogeneous and they match what will be generated by the automatic release script in `.github/workflows/prepare-release.yml`.

Standardize changelog dates to ISO-8601

---

.github/workflows/build.yml

Together with a weekly CI run (#100), this should ensure that we catch issues like #95 quickly when they appear on the nightly Rust channel.

Forbid warnings when building in CI

---

.dir-locals.el
Cargo.toml

It turns out I’m not using this as much as I expected — and I can always configure it in other ways if needed.

Remove Emacs config file from repository

---

.github/workflows/build.yml
Cargo.toml
src/contains_regex.rs
src/helpers.rs
src/html_root_url.rs
src/lib.rs
src/markdown_deps.rs
tests/version-numbers.rs

This PR adds three features, one for each macro, and allows a user who only needs one macro to avoid dependencies that are only needed for the other macros.
Feedback requested:
- Bikeshedding the feature names
- Deciding which features to turn on by default

Feature-gate tests to reduce dependencies

---

.github/workflows/build.yml
src/contains_substring.rs
src/helpers.rs
src/lib.rs

This function searches for the a template using a simple substring match. It is always enabled since it doesn’t need anything outside the standard library.

Add simple `check_contains_version` function

---

Cargo.toml
src/helpers.rs
src/html_root_url.rs
src/markdown_deps.rs

Based on steveklabnik/semver-parser@dc6c1077899d, I gather that we should use `semver` going forward.

Move from deprecated `semver-parser` to `semver`

---

src/helpers.rs

Before, a dependency specified as
```toml
[dependencies]
foo = ">= 1.2.3, < 2.0"
```
was ignored since it was deemed too complicated to check versions
requirements with multiple comparators.
We now handle such cases by checking every comparator individually.
Comparators which form a lower-bound for the version is checked. This
means that version requirements of the form
* `1.2` and `^1.2`
* `~1.2`
* `=1.2`
* `>1.2`
* `>=1.2`
* `1.2.*`
are all checked for compatibility with the actual crate version. If
the crate version is higher than the version requirement, an error is
returned.
Upper-build version requirements such as `<2.0` are ignored like
before.

Check version numbers in `=1.2.3` and `>1.2.3`, and `>=1.2.3`

---

src/lib.rs

The links became redundant with the introduction of “implied link reference definitions” or “intra-doc links” in Rust 1.48.

Remove unnecessary Markdown links

---

.github/workflows/prepare-release.yml
Cargo.toml
README.md
src/contains_regex.rs
src/helpers.rs
src/lib.rs
tests/version-numbers.rs

This macro compliments the existing `assert_contains_regex!`. While `assert_contains_regex!` implements the “exists” quantifier, the new macro implements a “for all” quantifier.
In more details, the macro uses two steps:
1. Replace `{version}` in the `template` by a regular expression which will match _any_ SemVer version number. This allows, say, `docs.rs/{name}/{version}/` to match old and outdated occurrences of your package.
2. Find all matches in the file and check each match against `template`. This time we replace `{version}` with `pkg_version` so that we can do an accurate comparison with the actual package version.
This allows you to ensure that, say, all `docs.rs` links are updated.
Fixes #72.

Add `assert_only_contains_regex!`

---

Cargo.toml

Following the advice from [1], this PR updates Cargo.toml to use precise version numbers for all dependencies. The latest versions at the time of writing are used.
Before, running
```
% cargo -Z minimal-versions update
% cargo test
```
failed on nightly because of a transitive dependency. Now it works again.
[1]: https://users.rust-lang.org/t/psa-please-specify-precise-dependency-versions-in-cargo-toml/71277

Use precise dependency versions in Cargo.toml

---

Cargo.toml

Migrate to the Rust 2021 edition

---

Cargo.toml
src/html_root_url.rs

This is one of a couple of my dependencies still requiring syn v1. So I took the liberty to update it to v2.
The only change necessary was replacing the code using `NestedMeta`, since that type is no longer available in syn. I replaced it with `Attribute::parse_nested_meta`.

Update syn to v2

---

src/lib.rs

The attribute is no longer recommended by the API guidelines, though there are use cases for people who host their documentation themselves and thus don’t use docs.rs. This should make it a little clearer when to use `assert_html_root_url_updated!`.

Explain the use of `html_root_url`

---

README.md

It now primarily contains the user-visible changes. Non-functional CI changes can be found in the repository log.

Simplify changelog

---

src/contains_regex.rs
src/contains_substring.rs
src/html_root_url.rs
src/markdown_deps.rs

I also inlined format arguments.

Run Clippy

---

src/contains_regex.rs
src/contains_substring.rs
src/html_root_url.rs
src/markdown_deps.rs

Due to https://github.com/rust-lang/rust-clippy/issues/11470, some format strings were not inlined in #135. Running Clippy with a stable compiler fixes the problem.

Apply Clippy again

---

.github/workflows/build.yml

GitHub disables a scheduled workflow if there has been no changes for some time (60 days). This makes the it counter-productive to have a schedule for this rarely updated repository.

Remove the scheduled build workflow

---

Cargo.toml
src/markdown_deps.rs

This pull request upgrades `pulldown-cmark` to `0.11` so that other projects using newer `pulldown-cmark` can have one less dependency.

Upgrade pulldown-cmark to 0.11
